routes/web.php
<?php
/**
 * Authentication routes
 *
 * All the routes here handles registration, login, password reset etc
 */
Route::get('/join', 'TalentJoinController@show')->name('talent.join-show');
Route::post('/join', 'TalentJoinController@store')->middleware('phone-number-setter')->name('talent.join');
Route::get('/join/plans', 'TalentJoinController@selectPlan')->name('join.plan-selection')->middleware('auth');
Route::get('/login', 'LoginController@login')->name('login');
Route::post('/login', 'LoginController@loginProcess')->name('login-process');
Route::post('/login', 'LoginController@loginProcess')->name('login-process');

/**
 * Password rest
 */
Route::get('/forgot-password', 'PasswordResetController@forgotPassword')->name('auth.forgot-password');
Route::post('/forgot-password', 'PasswordResetController@forgotPasswordPost')->name('auth.forgot-password-post');
Route::get('reset-password/{token}', 'PasswordResetController@resetPassword')->name('auth.reset-password');
Route::post('reset-password/{any}', 'PasswordResetController@setNewPassword')->name('auth.reset-password-process');
Route::get('/logout', 'UserAccount\LogoutController@logout')->name('account.logout');


/**
 * User account routes
 */
Route::group(['prefix' => 'account', 'middleware' => ['auth'], 'namespace' => 'UserAccount'], function() {
    Route::get('/', 'AccountController@home')->name('account.home');
    Route::get('/home', 'AccountDashboardController@index')->middleware('account-verify')->name('account.dashboard');
    Route::get('/profile', 'ProfileController@profile')->name('account.profile');
    Route::get('/profile/media', 'ProfileMediaController@index')->name('account.profile.media');
    Route::post('/profile/media', 'ProfileMediaController@store')->name('account.profile.media.store');
    Route::delete('/profile/media/{id}', 'ProfileMediaController@delete');
    Route::get('/profile/avatar', 'ProfileController@addAvatar')->name('account.profile.avatar');
    Route::get('/profile/settings', 'AccountSettingsController@profileSettings')->name('account.profile.settings');
    Route::get('/profile/settings/subscriptions', 'AccountSettingsController@subscriptions')->name('account.profile.settings.subscriptions');
    Route::post('/profile/password', 'AccountPasswordController@setNewPassword')->name('account.profile.password');

    Route::post('/profile/set-location', 'UserLocationController@store');

    Route::get('/packages/{id}/change', 'BillingPackage@changePackage')->name('account.change.package');
    Route::get('/packages/{id}/pricing', 'BillingPackage@getPricing');
    Route::get('/packages/{id}/pricing', 'BillingPackage@getPricing');
    Route::post('/packages/order-subscription', 'BillingPackage@orderSubscription');

    Route::get('/billing/{txf}/verify', 'BillingTransactionVerify@check');

    Route::get('/applications', 'ApplicationManagementController@index')->name('account.applications');


    Route::group(['prefix' => '/educations'], function() {

        Route::get('/', 'EducationManagementController@index');
        Route::post('/', 'EducationManagementController@store');
        Route::post('/{id}', 'EducationManagementController@update');
        Route::delete('/{id}', 'EducationManagementController@delete');

    });

    Route::group(['prefix' => '/productions'], function() {

        Route::get('/', 'ProductionDataController@index');
        Route::post('/invite', 'ProductionDataController@store');

    });


    /**
     * Account endpoints for ajax result
     */
    Route::group(['prefix' => 'api', 'namespace' => 'Api'], function() {

        Route::get('/profile', 'ProfileManagementController@showProfile')->name('account.api.show.profile');
        Route::post('/profile', 'ProfileManagementController@updateProfile')->name('account.api.profile');


        Route::get('/profile/medias', 'ProfileManagementController@getMedias')->name('account.api.show.medias');

        Route::get('/profile/appearance', 'AppearanceController@index')->name('account.api.appearance');
        Route::post('/profile/appearance', 'AppearanceController@store')->name('account.api.appearance.store');


        // account/api/profile/settings
        Route::group(['prefix' => 'profile/settings'], function() {

            Route::get('/', 'ProfileSettingsController@getProfileInfo');
        });

    });
});


Route::group(['prefix' => 'creator', 'namespace' => 'Creator'], function() {

    Route::get('/join', 'CreatorJoinController@index')->name('creator.join');
    Route::post('/join', 'CreatorJoinController@store')->name('creator.join.store')->middleware('phone-number-setter');

    Route::get('/company-profile-update', 'CreatorCompanyProfileUpdate@index')
                ->name('creator.company.profile-update');
    Route::post('/company-profile-update', 'CreatorCompanyProfileUpdate@store');

    Route::group(['prefix' => 'projects', 'namespace' => 'Project', 'middleware' => ['auth', 'account-verify']], function() {
        Route::get('/', 'CastingProjectController@index')->name('casting.projects.index');
        Route::get('/post', 'ProjectController@index')->name('creator.projects.new');
        Route::post('/{id}', 'ProjectController@store')->name('creator.projects.post');
        Route::get('/{id}/applications', 'ProjectApplicationsController@index')->name('creator.projects.applications');
        Route::post('/{id}/basins/{applicationId}', 'ProjectBasinController@store');
        Route::get('/{id}/applications-feeds', 'ProjectApplicationsController@feeds');
        Route::post('/{id}/roles', 'ProjectController@storeRole')->name('creator.projects.store.role');
        Route::get('/{id}/roles', 'ProjectController@getRoles')->name('creator.projects.get.roles');
        Route::delete('/{id}/roles/{roleId}', 'ProjectController@deleteRole')->name('creator.projects.delete.role');
        Route::get('/{id}/locations', 'ProjectController@getLocations')->name('creator.projects.get.locations');
        Route::get('/{id}/{status}', 'ProjectController@show')->name('creator.projects.show');
        Route::post('/{id}/attach-country', 'ProjectController@attachCountry');
        Route::post('/{id}/attach-city', 'ProjectController@attachCity');
        Route::post('/{id}/locations', 'ProjectController@addLocation')->name('creator.projects.add.location');
        Route::post('/{id}/locations-with-dates', 'ProjectController@addLocationWithDates')->name('creator.projects.add.location.with.dates');
        Route::get('/{id}/locations-with-dates/{locationId}', 'ProjectController@getLocationDates')->name('creator.projects.get.location.dates');
        Route::delete('/{id}/locations/{location}', 'ProjectController@removeLocation')->name('creator.projects.remove.location');
        Route::delete('/{id}/locations-with-dates/{locationId}/{datePId}', 'ProjectController@removeLocationDate');

        /**
         * Applying for application
         */

        });


    Route::group(['prefix' => 'notes', 'namespace' => 'Note', 'middleware' => ['auth']], function() {
        Route::get('/{userId}', 'NewNoteController@show');
        Route::post('/{userId}', 'NewNoteController@store');
        Route::delete('/{userId}', 'NewNoteController@delete');
    });
});

Route::group(['prefix' => 'casting-calls', 'namespace' => 'Core'], function() {

    Route::get('/', 'CastingCallsController@index')->name('casting-calls');
    Route::get('/feeds', 'CastingCallsController@getAll');
    Route::get('/feeds/{projectId}', 'CastingCallsController@show');
    Route::get('/{id}', 'SingleCastingCallController@index')->name('single.casting-call');
    Route::post('/{projectId}/draft-apply', 'ApplyToProjectRoleController@draftStore');
    Route::post('/{projectId}/apply', 'ApplyToProjectRoleController@store');
    Route::post('/{projectId}/apply/{applicationId}/media/{mediaTypeId}', 'ApplyToProjectRoleAddMediaController@store');

});

Route::group(['prefix' => 'talents', 'namespace' => 'Core'], function() {

    Route::get('/', 'TalentController@index')->name('talents');
    Route::get('/feeds', 'TalentFeedController@index')->name('talent.feed');
    Route::get('/feeds/{userId}', 'TalentFeedController@show')->name('talent.feed.show');

});

Route::get('/geo/search', 'Core\HomePageController@geo');

Route::get('/', 'Core\HomePageController@home')->name('home');
Route::get('/performers/how-it-works', 'Core\HomePageController@performHowItWorks')->name('performer.how-it-works');
Route::get('/creators/how-it-works', 'Core\CreatorPublicController@creatorHowItWorks')->name('creator.how-it-works');

Route::group(['prefix' => 'utilities', 'namespace' => 'Utilities'], function() {

    Route::get('/body-sizes', 'BodySizeController@index');
    Route::get('/eye-colors', 'EyeColorController@index');
    Route::get('/hair-colors', 'HairColorController@index');
    Route::get('/appearance', 'AppearanceController@index')->middleware('auth');

    Route::get('/skills', 'ProfileSkillController@index');
    Route::post('/skills', 'ProfileSkillController@store');


});

Route::group(['prefix' => 'graph', 'namespace' => 'Graph', 'as' => 'graph.'], function() {

    Route::get('/skills', 'SkillsController@index')->name('skills');

});

Route::get('/partnership', 'Core\PartnershipController@index')->name('partnership');
Route::get('/services/terms', 'Core\ServciesController@terms')->name('terms-of-services');
Route::get('/about', 'Core\AboutController@index')->name('about');

Route::get('/verify', 'Core\VerificationController@index')->middleware('auth')->name('verify');
Route::get('/verify/activation', 'Core\VerificationController@activate')->middleware('auth')->name('verify.activate');

Route::get('/u/{username}', 'Core\PublicProfileController@index')->name('public.profile');
Route::get('/u/{username}/media', 'Core\PublicProfileController@media')->name('public.profile.media');
Route::get('/u/{username}/appearance', 'Core\PublicProfileController@appearance')->name('public.profile.appearance');

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Tags\HasTags;

class Profile extends Model
{
    use HasTags;

    protected $guarded = ['id', 'user_id'];

    protected $hidden = ['created_at', 'updated_at'];

    protected $dates = ['created_at', 'updated_at', 'subscription_expires'];

    protected $appends = ['age_range', 'place', 'url'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getStageNameAttribute($value)
    {
        $name = trim($value) ? $value : e($this->user->first_name) . ' ' . e($this->user->last_name);

        return trim($name) ? : 'Unknown';
    }

    public function getUrlAttribute($value)
    {
        return route('public.profile', $this->profile_url);
    }


    public function getGenderAttribute($value)
    {
        if(!$value) return 'unspecified';

        return $value;
    }

    public function getProfileUrlAttribute($value)
    {
        return $value ? $value : str_slug($this->user->first_name . ' ' . $this->user->last_name);
    }



    public function subscriptionActive()
    {

        if(!$this->subscription_expires) return false;

        return $this->subscription_expires->isFuture();
    }

    public function activateSubscriptionForMonths($months=1)
    {
        $fromDate = $this->subscription_expires;
        if(!$fromDate)
            $fromDate = now();
        $this->subscription_expires = $fromDate->addMonths($months)->addHour(1);
        $this->save();
    }

    public function cancel()
    {
        $this->subscription_canceled = now();
        $this->save();
    }

    public function isCanceled()
    {
        return $this->subscription_canceled !== null;
    }

    public function notCanceled()
    {
        return !$this->isCanceled();
    }

    public function medias()
    {
        return $this->morphMany(Media::class, 'mediable');
    }

    public function addMedia($name, $url, $type, $mime=null)
    {
        return $this->medias()->create([
                'name' => $name,
                'type' => $type,
                'url' => $url,
                'mime' => $mime
        ]);
    }

    public function scopePublic($query)
    {
        $query->where('is_public', true);
    }

    public function getAgeRangeAttribute($key)
    {

        $yob = intval($this->yob); // year of birth

        if(!$yob) return 'Unknown';
        $age = date('Y') - $yob;

        return $age <= 18 ? '17-' . ($age  + 4) : ($age - 2) . '-' . ( $age + 4);
    }

    public function getPlaceAttribute()
    {

        $location = $this->location ? $this->location->name : $this->user->country->name;

        return  $location;

    }


    public function location()
    {
        return $this->belongsTo(Country::class, 'location_id');
    }


    public function getCompanyDisplayName()
    {
        return $this->company ? $this->company : $this->user->first_name;
    }

    public function built()
    {
        return $this->profile_url && $this->medias()->count() > 0;
    }

}

app/Http/Controllers/Core/CastingCallsController.php
<?php

namespace App\Http\Controllers\Core;

use App\Http\Controllers\Controller;
use App\Http\Resources\Ethnicity;
use App\Services\CategoryService;
use Illuminate\Http\Request;

/**
 * Class CastingCallsController
 *
 * @package \App\Http\Controllers\Core
 */
class CastingCallsController extends Controller
{
    private $categoryService = null;

    public function __construct(CategoryService $categoryService)
    {
        $this->categoryService = $categoryService;
    }

    /**
     * GET /casting-calls
     *
     * @return mixed
     */
    public function index()
    {
        $categories = $this->categoryService->getActiveCategories();
        $ethnicities = \App\Ethnicity::select('id', 'name')->get();

        return view('casting-calls.index')
                    ->with('ethnicities', $ethnicities)
                    ->with('categories', $categories);
    }

    /**
     * /casting-calls/feeds
     * @param $request
     * @return mixed
     */
    public function getAll(Request $request)
    {
        $filters = $request->only(
                    'role_gender',
                         'production_type',
                         'is_paid', 'union_type',
                            'ethnicities', 'min_age', 'max_age'
                        );

        return \App\Ajizzy\Project::fetchProjects($filters);
    }

    /**
     * /casting-calls/feeds/{projectId}
     */

    public function show($projectId)
    {

        $project = \App\Ajizzy\Project::findOneOrFail($projectId);

        return $project;

    }
}

resources/views/casting-calls/_similar.blade.php
<div class="widget widget--similar-calls widget-transparent border-0 p-0 py-2">
    <h3 class="section-title--bordered">
        Similar calls
    </h3>
    <ul class="list-unstyled widget-list-items">

        @foreach($similar as $proj)
        <li>
            <h6 class="category-title">{{$proj->category->name}}</h6>
            <h4><a href="{{route('single.casting-call', $proj->id)}}">{{$proj->title}}</a></h4>
        </li>
        @endforeach

    </ul>
</div>

resources/views/casting-calls/index.blade.php
@extends('layouts.post')

@section('title')Open Casting Calls & Auditions Near You | Ajizzy @endsection
@section('keywords')Acting Jobs, Modeling Jobs, Entertainment jobs, latest modeling jobs, latest casting calls, @parent @endsection

@section('content')
    <div class="mid-section" id="calls">

        <casting-calls-wrapper :categories="{{$categories}}" :ethnicities="{{$ethnicities}}">
            <div class="container">loading..<i class="fas fa-spinner fa-spin"></i></div>
        </casting-calls-wrapper>
    </div>

@endsection

@section('footer_script')
    <script src="{{asset('assets/ajizzy/js/project/casting-calls.js')}}"></script>
@endsection

resources/views/casting-calls/single.blade.php
@extends('layouts.post')

@section('title'){{$project->title}} - Ajizzy @endsection

@section('description'){{Str::limit($project->description)}}@endsection

@section('content')
    <div class="mid-section" role="body" id="single">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="section-header">
                        <h1 class="section-header--title">{{$project->title}}</h1>
                    </div>
                    <div class="prod-listing__info">
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="prod-listing__info__section">
                                    <span class="category-label">CATEGORY:</span>
                                    <a href="/casting/?pt=56&amp;pt=107" class="tag category">{{$project->category->parent->name}}</a>
                                    <a href="/casting?pt=56&amp;pt=76" class="tag sub-category">{{$project->category->name}}</a>
                                </div>
                                <div class="prod-listing__info__section">
                                    <span class="tag-label">TAGS:</span>
                                    <a class="tag paid" href="/casting-calls/?compensation=true">Paid</a>
                                </div>
                                <div class="prod-listing__info__section">
                                    <span class="expires-text">
                                        <span class="expires-text--label">EXPIRES:</span>
                                        <span class="expires-text--date">{{$project->formatted_expiry_date}}</span>
                                    </span>
                                </div>
                                <div class="prod-listing__info__section share">
                                    <span class="share-label">SHARE:</span>
                                    <a href="https://www.facebook.com/sharer/sharer.php?u={{route('single.casting-call', $project->id)}}" target="_blank" class="share-icon facebook"></a>
                                    <a
                                        href="https://twitter.com/intent/tweet?text=Open Casting Call: {{$project->title}}&url={{route('single.casting-call', $project->id)}}&hashtags=ajizzy,african talents,creators,actors,models" target="_blank" class="share-icon twitter"></a>
                                    <a href="mailto:?subject=Open Casting Call: {{$project->title}}&body=A new role has just been posted on ajizzy.com. Hurry now and reserve your space at {{route('single.casting-call', $project->id)}}" target="_blank" class="share-icon email"></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="section-body">
                        <div class="casting--primary-information">
                            <div class="cast-author-category">Company / Agency</div>
                            <div class="cast-author-name">{{$project->company}}</div>
                            <div class="cast-crew">
                                {{str_limit($project->about_company,1000)}}
                            </div>
                            <div class="cast-description">
                                <h5>Production description</h5>
                                <p>{{$project->description}}</p>

                            </div>
                        </div>
                        <div class="casting--secondary-information">
                            <div class="casting--roles">
                                <h3>
                                    Roles
                                    <span class="expand-roles float-right">
                                        <a href="#">Expand all roles</a>
                                    </span>
                                </h3>

                                <div class="sub--section-content">
                                    <div class="accordion" id="available-roles">
                                        <div class="card pt-2 mb-0">
                                            @foreach($project->roles as $role)
                                            <div class="card-header" id="role{{$role->id}}">
                                                <h4 class="mb-0 card-header-title">
                                                    <a class="" data-toggle="collapse" href="#role{{$role->id}}Details" role="button" aria-expanded="false" aria-controls="roleOneDetails">{{$role->name}} ({{$role->roleType->name}}): <span class="role-meta">{{$role->gender}}, {{$role->min_age}}-{{$role->max_age}}</span>
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="role{{$role->id}}Details" class="collapse" aria-labelledby="role{{$role->id}}" data-parent="#available-roles">
                                                <div class="card-body">
                                                    @if($role->description)
                                                        <p>{{$role->description}}</p>
                                                    @else
                                                        <p>No specific description for this role. Just hit apply.</p>
                                                    @endif

                                                        @if($role->requires_nudity) <p>
                                                            <span class="badge badge-danger">This role requires nudity</span>
                                                        </p> @endif


                                                    @if(!in_array($role->id, $rolesApplied->toArray()))
                                                    <apply-for-role
                                                        :role="{{$role}}"
                                                        input-class="btn btn-sm btn-black btn__custom mt-3"
                                                        btn-text="Apply for this role"
                                                        key="{{$role->id}}"
                                                        :roles-applied="{{$rolesApplied}}"
                                                        :auth-check="{{auth()->user() ? 0 : 1}}">Loading..</apply-for-role>
                                                   @else
                                                       <p><button class="btn btn-success">Applied <i class="fas fa-check"></i></button></p>
                                                    @endif
                                                </div>
                                            </div>
                                           @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="casting--dates">
                                <h3>Rehearsal / Production Dates &amp; Locations</h3>
                                <div class="sub--section-content">
                                    <p>{{$project->loc}}</p>
                                </div>
                            </div>
                            <div class="casting--contracts">
                                <h3>Compensation & Union Contract Details</h3>
                                <div class="sub--section-content">
                                    <p>{{$project->compensation_detail}}</p>
                                </div>
                            </div>
                            <div class="casting--key-details">
                                <h3>Key Details</h3>
                                <div class="sub--section-content">
                                    <p>
                                        <span class="font-weight-bold text-capitalize">Seeking talent:</span>
                                        <br />
                                        @if($project->location == 'worldwide')
                                            Seeking talents worldwide.
                                        @else
                                        {{ucfirst($project->location)}}
                                            ({{$project->location === 'local' ? $project->country->name : 'Multiple locations'}})
                                            @endif
                                    </p>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4 aside">
                    <div class="widget widget--apply widget--bg-ajizzy">
                        <h3>Ready to apply?</h3>
                        <ready-to-apply-box :roles="{{$project->roles}}"></ready-to-apply-box>
                    </div>

                     @include('casting-calls._similar')


                </div>
            </div>
        </div>
    </div>

@endsection

@section('footer_script')
    <script src="{{asset('assets/ajizzy/js/project/casting-call-single.js')}}"></script>

@endsection