routes/web.php
<?php
/**
 * Authentication routes
 *
 * All the routes here handles registration, login, password reset etc
 */
Route::get('/join', 'TalentJoinController@show')->name('talent.join-show');
Route::post('/join', 'TalentJoinController@store')->middleware('phone-number-setter')->name('talent.join');
Route::get('/join/plans', 'TalentJoinController@selectPlan')->name('join.plan-selection')->middleware('auth');
Route::get('/login', 'LoginController@login')->name('login');
Route::post('/login', 'LoginController@loginProcess')->name('login-process');
Route::post('/login', 'LoginController@loginProcess')->name('login-process');

/**
 * Password rest
 */
Route::get('/forgot-password', 'PasswordResetController@forgotPassword')->name('auth.forgot-password');
Route::post('/forgot-password', 'PasswordResetController@forgotPasswordPost')->name('auth.forgot-password-post');
Route::get('reset-password/{token}', 'PasswordResetController@resetPassword')->name('auth.reset-password');
Route::post('reset-password/{any}', 'PasswordResetController@setNewPassword')->name('auth.reset-password-process');
Route::get('/logout', 'UserAccount\LogoutController@logout')->name('account.logout');


/**
 * User account routes
 */
Route::group(['prefix' => 'account', 'middleware' => ['auth'], 'namespace' => 'UserAccount'], function() {
    Route::get('/', 'AccountController@home')->name('account.home');
    Route::get('/home', 'AccountDashboardController@index')->middleware('account-verify')->name('account.dashboard');
    Route::get('/profile', 'ProfileController@profile')->name('account.profile');
    Route::get('/profile/media', 'ProfileMediaController@index')->name('account.profile.media');
    Route::post('/profile/media', 'ProfileMediaController@store')->name('account.profile.media.store');
    Route::delete('/profile/media/{id}', 'ProfileMediaController@delete');
    Route::get('/profile/avatar', 'ProfileController@addAvatar')->name('account.profile.avatar');
    Route::get('/profile/settings', 'AccountSettingsController@profileSettings')->name('account.profile.settings');
    Route::get('/profile/settings/subscriptions', 'AccountSettingsController@subscriptions')->name('account.profile.settings.subscriptions');
    Route::post('/profile/password', 'AccountPasswordController@setNewPassword')->name('account.profile.password');

    Route::post('/profile/set-location', 'UserLocationController@store');

    Route::get('/packages/{id}/change', 'BillingPackage@changePackage')->name('account.change.package');
    Route::get('/packages/{id}/pricing', 'BillingPackage@getPricing');
    Route::get('/packages/{id}/pricing', 'BillingPackage@getPricing');
    Route::post('/packages/order-subscription', 'BillingPackage@orderSubscription');

    Route::get('/billing/{txf}/verify', 'BillingTransactionVerify@check');

    Route::get('/applications', 'ApplicationManagementController@index')->name('account.applications');


    Route::group(['prefix' => '/educations'], function() {

        Route::get('/', 'EducationManagementController@index');
        Route::post('/', 'EducationManagementController@store');
        Route::post('/{id}', 'EducationManagementController@update');
        Route::delete('/{id}', 'EducationManagementController@delete');

    });

    Route::group(['prefix' => '/productions'], function() {

        Route::get('/', 'ProductionDataController@index');
        Route::post('/invite', 'ProductionDataController@store');

    });


    /**
     * Account endpoints for ajax result
     */
    Route::group(['prefix' => 'api', 'namespace' => 'Api'], function() {

        Route::get('/profile', 'ProfileManagementController@showProfile')->name('account.api.show.profile');
        Route::post('/profile', 'ProfileManagementController@updateProfile')->name('account.api.profile');


        Route::get('/profile/medias', 'ProfileManagementController@getMedias')->name('account.api.show.medias');

        Route::get('/profile/appearance', 'AppearanceController@index')->name('account.api.appearance');
        Route::post('/profile/appearance', 'AppearanceController@store')->name('account.api.appearance.store');


        // account/api/profile/settings
        Route::group(['prefix' => 'profile/settings'], function() {

            Route::get('/', 'ProfileSettingsController@getProfileInfo');
        });

    });
});


Route::group(['prefix' => 'creator', 'namespace' => 'Creator'], function() {

    Route::get('/join', 'CreatorJoinController@index')->name('creator.join');
    Route::post('/join', 'CreatorJoinController@store')->name('creator.join.store')->middleware('phone-number-setter');

    Route::get('/company-profile-update', 'CreatorCompanyProfileUpdate@index')
                ->name('creator.company.profile-update');
    Route::post('/company-profile-update', 'CreatorCompanyProfileUpdate@store');

    Route::group(['prefix' => 'projects', 'namespace' => 'Project', 'middleware' => ['auth', 'account-verify']], function() {
        Route::get('/', 'CastingProjectController@index')->name('casting.projects.index');
        Route::get('/post', 'ProjectController@index')->name('creator.projects.new');
        Route::post('/{id}', 'ProjectController@store')->name('creator.projects.post');
        Route::get('/{id}/applications', 'ProjectApplicationsController@index')->name('creator.projects.applications');
        Route::post('/{id}/basins/{applicationId}', 'ProjectBasinController@store');
        Route::get('/{id}/applications-feeds', 'ProjectApplicationsController@feeds');
        Route::post('/{id}/roles', 'ProjectController@storeRole')->name('creator.projects.store.role');
        Route::get('/{id}/roles', 'ProjectController@getRoles')->name('creator.projects.get.roles');
        Route::delete('/{id}/roles/{roleId}', 'ProjectController@deleteRole')->name('creator.projects.delete.role');
        Route::get('/{id}/locations', 'ProjectController@getLocations')->name('creator.projects.get.locations');
        Route::get('/{id}/{status}', 'ProjectController@show')->name('creator.projects.show');
        Route::post('/{id}/attach-country', 'ProjectController@attachCountry');
        Route::post('/{id}/attach-city', 'ProjectController@attachCity');
        Route::post('/{id}/locations', 'ProjectController@addLocation')->name('creator.projects.add.location');
        Route::post('/{id}/locations-with-dates', 'ProjectController@addLocationWithDates')->name('creator.projects.add.location.with.dates');
        Route::get('/{id}/locations-with-dates/{locationId}', 'ProjectController@getLocationDates')->name('creator.projects.get.location.dates');
        Route::delete('/{id}/locations/{location}', 'ProjectController@removeLocation')->name('creator.projects.remove.location');
        Route::delete('/{id}/locations-with-dates/{locationId}/{datePId}', 'ProjectController@removeLocationDate');

        /**
         * Applying for application
         */

        });


    Route::group(['prefix' => 'notes', 'namespace' => 'Note', 'middleware' => ['auth']], function() {
        Route::get('/{userId}', 'NewNoteController@show');
        Route::post('/{userId}', 'NewNoteController@store');
        Route::delete('/{userId}', 'NewNoteController@delete');
    });
});

Route::group(['prefix' => 'casting-calls', 'namespace' => 'Core'], function() {

    Route::get('/', 'CastingCallsController@index')->name('casting-calls');
    Route::get('/feeds', 'CastingCallsController@getAll');
    Route::get('/feeds/{projectId}', 'CastingCallsController@show');
    Route::get('/{id}', 'SingleCastingCallController@index')->name('single.casting-call');
    Route::post('/{projectId}/draft-apply', 'ApplyToProjectRoleController@draftStore');
    Route::post('/{projectId}/apply', 'ApplyToProjectRoleController@store');
    Route::post('/{projectId}/apply/{applicationId}/media/{mediaTypeId}', 'ApplyToProjectRoleAddMediaController@store');

});

Route::group(['prefix' => 'talents', 'namespace' => 'Core'], function() {

    Route::get('/', 'TalentController@index')->name('talents');
    Route::get('/feeds', 'TalentFeedController@index')->name('talent.feed');
    Route::get('/feeds/{userId}', 'TalentFeedController@show')->name('talent.feed.show');

});

Route::get('/geo/search', 'Core\HomePageController@geo');

Route::get('/', 'Core\HomePageController@home')->name('home');
Route::get('/performers/how-it-works', 'Core\HomePageController@performHowItWorks')->name('performer.how-it-works');
Route::get('/creators/how-it-works', 'Core\CreatorPublicController@creatorHowItWorks')->name('creator.how-it-works');

Route::group(['prefix' => 'utilities', 'namespace' => 'Utilities'], function() {

    Route::get('/body-sizes', 'BodySizeController@index');
    Route::get('/eye-colors', 'EyeColorController@index');
    Route::get('/hair-colors', 'HairColorController@index');
    Route::get('/appearance', 'AppearanceController@index')->middleware('auth');

    Route::get('/skills', 'ProfileSkillController@index');
    Route::post('/skills', 'ProfileSkillController@store');


});

Route::group(['prefix' => 'graph', 'namespace' => 'Graph', 'as' => 'graph.'], function() {

    Route::get('/skills', 'SkillsController@index')->name('skills');

});

Route::get('/partnership', 'Core\PartnershipController@index')->name('partnership');
Route::get('/services/terms', 'Core\ServciesController@terms')->name('terms-of-services');
Route::get('/about', 'Core\AboutController@index')->name('about');

Route::get('/verify', 'Core\VerificationController@index')->middleware('auth')->name('verify');
Route::get('/verify/activation', 'Core\VerificationController@activate')->middleware('auth')->name('verify.activate');

Route::get('/u/{username}', 'Core\PublicProfileController@index')->name('public.profile');
Route::get('/u/{username}/media', 'Core\PublicProfileController@media')->name('public.profile.media');
Route::get('/u/{username}/appearance', 'Core\PublicProfileController@appearance')->name('public.profile.appearance');

app/Profile.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Tags\HasTags;

class Profile extends Model
{
    use HasTags;

    protected $guarded = ['id', 'user_id'];

    protected $hidden = ['created_at', 'updated_at'];

    protected $dates = ['created_at', 'updated_at', 'subscription_expires'];

    protected $appends = ['age_range', 'place', 'url'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getStageNameAttribute($value)
    {
        $name = trim($value) ? $value : e($this->user->first_name) . ' ' . e($this->user->last_name);

        return trim($name) ? : 'Unknown';
    }

    public function getUrlAttribute($value)
    {
        return route('public.profile', $this->profile_url);
    }


    public function getGenderAttribute($value)
    {
        if(!$value) return 'unspecified';

        return $value;
    }

    public function getProfileUrlAttribute($value)
    {
        return $value ? $value : str_slug($this->user->first_name . ' ' . $this->user->last_name);
    }



    public function subscriptionActive()
    {

        if(!$this->subscription_expires) return false;

        return $this->subscription_expires->isFuture();
    }

    public function activateSubscriptionForMonths($months=1)
    {
        $fromDate = $this->subscription_expires;
        if(!$fromDate)
            $fromDate = now();
        $this->subscription_expires = $fromDate->addMonths($months)->addHour(1);
        $this->save();
    }

    public function cancel()
    {
        $this->subscription_canceled = now();
        $this->save();
    }

    public function isCanceled()
    {
        return $this->subscription_canceled !== null;
    }

    public function notCanceled()
    {
        return !$this->isCanceled();
    }

    public function medias()
    {
        return $this->morphMany(Media::class, 'mediable');
    }

    public function addMedia($name, $url, $type, $mime=null)
    {
        return $this->medias()->create([
                'name' => $name,
                'type' => $type,
                'url' => $url,
                'mime' => $mime
        ]);
    }

    public function scopePublic($query)
    {
        $query->where('is_public', true);
    }

    public function getAgeRangeAttribute($key)
    {

        $yob = intval($this->yob); // year of birth

        if(!$yob) return 'Unknown';
        $age = date('Y') - $yob;

        return $age <= 18 ? '17-' . ($age  + 4) : ($age - 2) . '-' . ( $age + 4);
    }

    public function getPlaceAttribute()
    {

        $location = $this->location ? $this->location->name : $this->user->country->name;

        return  $location;

    }


    public function location()
    {
        return $this->belongsTo(Country::class, 'location_id');
    }


    public function getCompanyDisplayName()
    {
        return $this->company ? $this->company : $this->user->first_name;
    }

    public function built()
    {
        return $this->profile_url && $this->medias()->count() > 0;
    }

}

app/Http/Controllers/Creator/CreatorCompanyProfileUpdate.php
<?php

namespace App\Http\Controllers\Creator;
use App\Ajizzy\GoogleAddressChecker;
use App\Country;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller as BaseController;
/**
 * Class CreatorCompanyProfileUpdate
 *
 * @package \App\Http\Controllers\Creator
 */
class CreatorCompanyProfileUpdate extends BaseController
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * GET /creator/company-profile-update
     */
    public function index()
    {

       $loc = auth()->user()->profile->location ?: auth()->user()->country;


       $profileData = [
           'company' => auth()->user()->profile->company,
           'about_company' => auth()->user()->profile->about_company,
           'place_id' => ($loc && isset($loc->id)) ? $loc->id : '',
           'location' => ($loc && $loc->official) ? $loc->official : 'No location set'
       ];


        return view('creator.update-company-profile', ['country' => auth()->user()->country, 'profile' => $profileData]);
    }

    /**
     * POST /creator/company-profile-update
     */
    public function store(Request $request)
    {

        $loc = auth()->user()->profile->location;

        $location = \App\Country::find($request->input('place_id'));
        $placeId = trim($request->input('place_id'));


        if(!$location && $placeId) {

                if($loc && $loc !== $placeId) {
                    $location =  GoogleAddressChecker::getInfo($placeId);
                    if(!$location)
                        return ['status' => 'error',  'message' => 'Unable to add city. Could be an issue with google service'];
                    else
                        $request['location_id'] = $location ? $location->id : '';
                } else {
                    $request['location_id'] = $loc;
                }
        } else {
            $request['location_id'] = $location->id;
        }





        auth()->user()->profile->update($request->only('location_id', 'company', 'about_company'));

        return ['status' => 'ok'];


    }
}

app/Http/Controllers/Creator/CreatorJoinController.php
<?php

namespace App\Http\Controllers\Creator;

use App\Country;
use App\Http\Requests\CreateNewCreatorRequest;
use App\Occupation;
use App\User;
use Illuminate\Routing\Controller as BaseController;

/**
 * Class CreatorJoinController
 *
 * @package \App\Http\Controllers\Creator
 */
class CreatorJoinController extends BaseController
{

    /**
     * GET /creator/join
     */
    public function index()
    {
        return view('auth.creator-join')
                ->with('occupations', Occupation::getAll())
                ->with('countries', Country::getAll());
    }

    /**
     * POST /creator/join
     * @param \App\Http\Requests\CreateNewCreatorRequest $request
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateNewCreatorRequest $request)
    {
        $data = $request->validated();


        $data['phone'] = formatPhone(request('phone'), $request->db_country->cca2);
        $data['country_id'] = $request->db_country->id;
        $data['account_type'] = User::ACCOUNT_TYPE_CREATOR;


        $user = User::create($data);

        $user->createProfile($request->only(['company', 'title', 'occupation_id']));

        auth()->loginUsingId($user->id);

        session()->forget('location');

        return redirect()->route('creator.company.profile-update');
    }

}

app/Http/Controllers/Creator/Project/CastingProjectController.php
<?php

namespace App\Http\Controllers\Creator\Project;

use App\User;
use Illuminate\Routing\Controller as BaseController;
/**
 * Class CastingProjectController
 *
 * @package \App\Http\Controllers\Creator\Project
 */
class CastingProjectController extends BaseController
{

    /**
     * GET /creator/projects
     */
    public function index()
    {
        $projectsCount = auth()->user()->projects()->count();
        $projects = auth()->user()->projects()->withCount(['applications' => function($query){
            $query->valid();
        }])->latest()->paginate(10);

        $notedTalents = User::getLatestNotes(auth()->user(), 3);

        return view('creator.projects.index')
                ->with(compact('projectsCount', 'projects', 'notedTalents'));
    }
}

resources/views/creator/projects/_application-action.blade.php
<div class="dropdown">
    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v"></i> action
    </a>
    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
        <a class="dropdown-item" href="?basin=green&application={{$talent->id}}">Approve</a>
        <a class="dropdown-item" href="?basin=yellow&application={{$talent->id}}">Put in review</a>
        <a class="dropdown-item" href="?basin=red&application={{$talent->id}}">Reject</a>
    </div>
</div>

resources/views/creator/projects/_application-filter-form.blade.php
<form class="form-inline" action="" method="get">
    <div class="form-group mb-2">
        <label for="Role" class="sr-only">Role</label>
        <select name="role" id="Role" class="form-control form-control-sm">
            <option value="">Select Role</option>
            @foreach($project->roles as $r)
                <option value="{{$r->id}}" {{ app('request')->input('role') === $r->id ? 'selected="selected"': '' }}>{{$r->name}}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group mb-2 mx-sm-3">
        <label for="status" class="sr-only">Status</label>
        <select name="status" id="status" class="form-control form-control-sm">
            <option value="">Status</option>
            @foreach($status as $key=>$s)
                <option value="{{$key}}" {{ app('request')->input('status') === $key ? 'selected="selected"': '' }}>{{$s}}</option>
            @endforeach
        </select>
    </div>

    <div class="form-group mx-sm-3 mb-2">
        <label for="q" class="sr-only">Query</label>
        <input type="text" class="form-control form-control-sm" name="q" value="{{app('request')->input('q')}}" id="q" placeholder="Search">
    </div>
    <button type="submit" class="btn btn-darker mb-2 btn-sm" name="action" value="filter">Filter</button>
    <button type="submit" class="btn btn-darker mb-2 btn-sm" name="action" value="download"><i class="fas fa-download"></i> Download</button>
    <a href="{{route('creator.projects.applications', $project->id)}}" class="btn btn-secondary mb-2 btn-sm" name="filter">Reset</a>
</form>

resources/views/creator/projects/applications.blade.php
@extends('layouts.main')

@section('content')

    <div class="mid-section" role="body">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <!-- Card header -->
                        <div class="card-header border-0">
                            <div class="row">
                                <div class="col-6">
                                    <h3 class="mb-0">Applications: {{$project->title}}</h3>
                                </div>
                                <div class="col-6 text-right">
                                    <a href="{{route('casting.projects.index')}}" class="btn btn-sm btn-dark btn-round btn-icon" data-toggle="tooltip" data-original-title="Go to dashboard">
                                        <span class="btn-inner--icon"><i class="fas fa-film"></i></span>
                                        <span class="btn-inner--text">Projects</span>
                                    </a>
                                </div>
                                <div class="col-12">
                                    To approve/reject an application, click on "action".
                                </div>

                                <div class="col-12">
                                    <br />
                                    @include('creator.projects._application-filter-form')
                                </div>
                            </div>

                        </div>
                        <!-- Light table -->
                        <div class="table-responsive">
                            <table class="table align-items-center table-flush table-striped">
                                <thead class="thead-light">
                                <tr>
                                    <th>Talent Details</th>
                                    <th>Contact</th>
                                    <th>Status</th>
                                    <th>Media</th>
                                    <th>Applied On</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <tbody class="list">
                                @foreach($applications as $talent)
                                <tr>
                                    <th scope="row">
                                        <div class="media align-items-center">
                                            <a href="#" class="avatar rounded-circle mr-3">
                                                @if($talent->owner->profile->medias)
                                                    <img alt="{{$talent->owner->profile->stage_name}}" src="{{$talent->owner->profile->medias[0]->url}}">
                                                @else
                                                    no avatar
                                                @endif
                                            </a>
                                            <div class="media-body">
                                                <span class="name mb-0 text-sm"><a href="{{route('public.profile', $talent->owner->profile->profile_url)}}" target="_blank">{{$talent->owner->profile->stage_name}}</a></span>
                                                <br />
                                                Role: {{$talent->role->name}}
                                            </div>
                                        </div>
                                    </th>
                                    <td class="budget">
                                        <a href="mailto:{{$talent->owner->email}}">{{$talent->owner->email}}</a><br />
                                        <a href="tel:{{$talent->owner->phone}}">{{$talent->owner->phone}}</a>
                                    </td>
                                    <td>
                                      <span class="badge badge-dot mr-4">
                                        <i class="bg-{{$talent->getBasinClass()}}"></i>
                                        <span class="status">{{$talent->getBasinMessage()}}</span>
                                      </span> @include('creator.projects._application-action')
                                    </td>
                                    <td>
                                        @if($talent->medias)
                                        <div class="avatar-group">
                                            @foreach($talent->medias as $m)
                                            <a href="?media={{$m->id}}&application={{$talent->id}}" target="{{$m->mediaType->input_type === 'upload' ? '_blank' : '_self'}}" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="{{$m->mediaType->name}}">
                                                @if($m->mediaType->input_type === 'upload')
                                                    <i class="fas fa-download"></i>
                                                @else
                                                    <i class="fas fa-file-alt"></i>
                                                @endif
                                            </a>
                                            @endforeach
                                        </div>
                                         @else
                                            <strong>No Media</strong>
                                       @endif
                                    </td>

                                    <td>
                                        <div class="d-flex align-items-center">{{$talent->formatted_created}}</div>
                                    </td>
                                    <td class="text-right">

                                    </td>
                                </tr>
                                  @endforeach
                                </tbody>
                            </table>
                            {!! $applications->links() !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/creator/projects/index.blade.php
@extends('layouts.main')

@section('content')
    <div class="mid-section" role="body">
        <div class="container">
            <div class="row">
                <div class="col-md-12 section--header">
                    <div class="row">
                        <div class="col-sm-6 col-xs-7 col-12">
                            <h1 class="section-header--title border-0">Your Projects</h1>
                            <p class="pb-3">To manage applications, click on <strong>"Applications"</strong></p>
                        </div>
                        <div class="col-sm-6 col-xs-5 col-12 text-md-right mb-4 mb-md-0">
                            <a href="{{route('creator.projects.new')}}" class="btn btn-sm btn-outline-darker"><i class="far fa-plus-square"></i> Post a Job</a>
                            <a href="#" class="btn btn-sm btn-outline-darker"><i class="fas fa-question"></i> Help</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8">


                    <div id="productions" class="card">
                        <div class="card-header">
                            <h5 class="h3 mb-0">My Productions (<span class="post-item-total">{{$projectsCount}}</span>)</h5>
                        </div>
                        <div class="card-body p-0">
                            <ul class="list-group list-group-flush list">
                               @foreach($projects as $project)
                                    <li class="list-group-item p-0">
                                        <div class="row mx-0 align-items-center panel__content--production">
                                            <div class="col-lg-6 col-md-12 col-sm-12">
                                                <h4 class="mb-0 collapsed" data-toggle="collapse" data-target="#production{{$project->id}}" aria-expanded="false" aria-controls="productionExample2"><span class="status draft">{{$project->status === 'drafted' ? '(Drafted)': ''}}</span>{{$project->title}}
                                                   </h4>
                                                <p class="text-sm mb-0">
                                                    <a class="menu-help-text"
                                                       href="{{route('creator.projects.applications', $project->id)}}">{{$project->applications_count}} application{{$project->applications_count > 1 ?  's' :  ''}}</a>
                                                </p>
                                            </div>
                                            <div class="col-lg-6 col-md-12 col-sm-12 text-lg-right">
                                                <a
                                                    class="btn btn-link btn-sm"
                                                    data-toggle="tooltip"
                                                    title="Manage applications"
                                                    href="{{route('creator.projects.applications', $project->id)}}"><i class="fas fa-tasks"></i> Applications</a>

                                                <a
                                                    href="{{route('creator.projects.show', ['id' => $project->id, 'status' => $project->status])}}"
                                                    class="btn  btn-link btn-sm"
                                                    data-toggle="tooltip"
                                                    title="Modify the project"> <i class="far fa-edit"></i> Edit</a>
                                                <a
                                                    class="btn  btn-link btn-sm"
                                                    data-toggle="tooltip"
                                                    title="Open project page"
                                                    href="{{$project->public_link}}"><i class="far fa-eye"></i> View</a>
                                            </div>
                                        </div>
                                        <div class="collapse" id="production{{$project->id}}" style="">
                                            <div class="prod__status">
                                                Status: <span class="prod__status--info">{{ucfirst($project->status)}}</span>
                                                Date Created: <span class="prod__status--info">{{$project->created_at->toDateString()}}</span>
                                                Date Expires: <span class="prod__status--info">{{$project->expires_at}}</span>
                                                Email Notification: <span class="prod__status--info">Daily Digest</span>
                                            </div>
                                        </div>
                                    </li>
                               @endforeach
                            </ul>
                        </div>
                    </div>
                    {!! $projects->links() !!}
                </div>
                <div class="col-md-4">
                   @include('account.latest-notes')
                </div>
            </div>
        </div>
    </div>
@endsection